#!/usr/bin/env python3
"""
Build map-data.bundle.js from all itinerary folders.

Usage:
    python build_map.py

Scans continent directories (europe/, asia/, africa/) for sub-folders
containing map-data.json and a .md file. Outputs map-data.bundle.js.
"""

import json
import re
from pathlib import Path

CONTINENTS = ["europe", "asia", "africa", "oceania"]
BUNDLE_PATH = Path("map-data.bundle.js")


def escape_js_template(s: str) -> str:
    return s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def find_md_file(folder: Path) -> Path | None:
    md_files = list(folder.glob("*.md"))
    if not md_files:
        return None
    # If multiple, prefer one that looks like the main itinerary doc
    for f in md_files:
        if "执行手册" in f.name or "规划" in f.name or "攻略" in f.name:
            return f
    return md_files[0]


def build():
    index = []
    plans = {}
    contents = {}
    image_dirs = {}

    for continent in CONTINENTS:
        continent_path = Path(continent)
        if not continent_path.is_dir():
            continue
        for folder in sorted(continent_path.iterdir()):
            if not folder.is_dir():
                continue
            map_data_file = folder / "map-data.json"
            md_file = find_md_file(folder)
            if not map_data_file.exists():
                print(f"⚠️  Skipping {folder}: map-data.json not found")
                continue
            if not md_file:
                print(f"⚠️  Skipping {folder}: no .md file found")
                continue

            map_data = json.loads(map_data_file.read_text(encoding="utf-8"))
            plan_id = map_data.get("plan_id")
            if not plan_id:
                # Fallback to folder name
                plan_id = folder.name
                map_data["plan_id"] = plan_id

            md_text = md_file.read_text(encoding="utf-8")

            index.append({
                "plan_id": plan_id,
                "name": map_data.get("name", plan_id),
                "continent": continent,
                "color": map_data.get("color", "#9ecbf3"),
                "center": map_data.get("center", [0, 0]),
                "zoom": map_data.get("zoom", 5),
            })

            plans[plan_id] = {
                "points": map_data.get("points", []),
                "routes": map_data.get("routes", []),
            }

            contents[plan_id] = escape_js_template(md_text)
            image_dirs[plan_id] = f"./{continent}/{folder.name}/images/"

            print(f"✅ Added {plan_id} ({continent})")

    # Sort index by continent then name for stable output
    index.sort(key=lambda x: (x["continent"], x["name"]))

    lines = [
        "// Auto-generated by build_map.py — do not edit manually\n",
        "window.ITINERARY_INDEX = " + json.dumps(index, ensure_ascii=False, indent=2) + ";\n",
        "\n",
        "window.ITINERARY_PLANS = " + json.dumps(plans, ensure_ascii=False, indent=2) + ";\n",
        "\n",
        "window.ITINERARY_IMAGE_DIRS = " + json.dumps(image_dirs, ensure_ascii=False, indent=2) + ";\n",
        "\n",
        "window.ITINERARY_CONTENTS = {\n",
    ]

    for plan_id in sorted(contents.keys()):
        md = contents[plan_id]
        lines.append(f"  {json.dumps(plan_id)}: `{md}`,\n")

    lines.append("};\n")

    BUNDLE_PATH.write_text("".join(lines), encoding="utf-8")
    print(f"\n🗺️  Bundle written to {BUNDLE_PATH} ({len(index)} plans)")


if __name__ == "__main__":
    build()
